permalink: /:categories/:title/
collections:
  agenda:
    output: true
    permalink: /:collection/:title/
  homework:
    output: true
    permalink: /:collection/:title/
defaults:
  -
    scope:
      path: ""
      type: "agenda"
    values:
      layout: "agenda"
  -
    scope:
      path: ""
      type: "homework"
    values:
      layout: "homework"
relative_permalinks: false
future: false
